# Generated by Django 2.0.3 on 2018-03-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('siti', models.TextField()),
                ('punkt', models.TextField()),
                ('strid', models.TextField()),
                ('dom', models.TextField()),
                ('korp', models.TextField()),
                ('kv', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='adres',
            name='adres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakaz.zakaz'),
        ),
    ]
